### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by stevepeak**
Debugging coverage. Please do not merge. Thank you!

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I had travis ignoring pull requests for this repo. Turning it on for now.

**Comment by stevepeak** [comment]
Thanks @DarthGandalf I'm getting really close here, but having trouble fully understanding gcov output. For example:

```
        -:    0:Source:../include/znc/Config.h
        -:    0:Programs:126
        -:    1:/*EOF*/
  ...
        -:   34:/*EOF*/
        -:   35:/*EOF*/
function _ZN7CConfigC2ERKS_ called 0 returned 0% blocks executed 0%
function _ZN7CConfigD2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2ERKS_ called 383 returned 100% blocks executed 80%
function _ZN7CConfigD2Ev called 541 returned 100% blocks executed 100%
function _ZN7CConfigD2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2EOS_ called 36 returned 100% blocks executed 100%
function _ZN7CConfigC2ERKS_ called 0 returned 0% blocks executed 0%
function _ZN7CConfigD2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigD2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigD2Ev called 0 returned 0% blocks executed 0%
      960:   36:/*EOF*/
call    0 never executed
call    1 never executed
branch  2 never executed
branch  3 never executed
unconditional  4 never executed
call    5 never executed
call    6 never executed
call    7 never executed
call    8 returned 383
call    9 returned 383
branch 10 taken 383 (fallthrough)
branch 11 taken 0 (throw)
unconditional 12 taken 383
call   13 never executed
call   14 returned 541
call   15 returned 541
call   16 never executed
call   17 never executed
call   18 returned 36
call   19 returned 36
call   20 never executed
call   21 never executed
branch 22 never executed
branch 23 never executed
unconditional 24 never executed
call   25 never executed
call   26 never executed
call   27 never executed
call   28 never executed
call   29 never executed
call   30 never executed
call   31 never executed
        -:   37:/*EOF*/
function _ZN7CConfigC2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2Ev called 122 returned 100% blocks executed 53%
function _ZN7CConfigC2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2Ev called 0 returned 0% blocks executed 0%
function _ZN7CConfigC2Ev called 0 returned 0% blocks executed 0%
      122:   38:/*EOF*/
call    0 never executed
call    1 never executed
branch  2 never executed
branch  3 never executed
call    4 never executed
call    5 never executed
call    6 never executed
branch  7 never executed
branch  8 never executed
call    9 never executed
unconditional 10 never executed
unconditional 11 never executed
call   12 never executed
call   13 never executed
unconditional 14 never executed
call   15 never executed
unconditional 16 never executed
call   17 never executed
call   18 returned 122
call   19 returned 122
branch 20 taken 122 (fallthrough)
branch 21 taken 0 (throw)
call   22 returned 122
call   23 returned 122
call   24 returned 122
branch 25 taken 122 (fallthrough)
branch 26 taken 0 (throw)
call   27 returned 122
unconditional 28 taken 122
unconditional 29 never executed
call   30 never executed
call   31 never executed
unconditional 32 never executed
call   33 never executed
unconditional 34 never executed
call   35 never executed
call   36 never executed
call   37 never executed
branch 38 never executed
branch 39 never executed
call   40 never executed
call   41 never executed
call   42 never executed
branch 43 never executed
branch 44 never executed
call   45 never executed
unconditional 46 never executed
unconditional 47 never executed
call   48 never executed
call   49 never executed
unconditional 50 never executed
call   51 never executed
unconditional 52 never executed
call   53 never executed
call   54 never executed
call   55 never executed
branch 56 never executed
branch 57 never executed
call   58 never executed
call   59 never executed
call   60 never executed
branch 61 never executed
branch 62 never executed
call   63 never executed
unconditional 64 never executed
unconditional 65 never executed
call   66 never executed
call   67 never executed
unconditional 68 never executed
call   69 never executed
unconditional 70 never executed
call   71 never executed
call   72 never executed
call   73 never executed
branch 74 never executed
branch 75 never executed
call   76 never executed
call   77 never executed
call   78 never executed
branch 79 never executed
branch 80 never executed
call   81 never executed
unconditional 82 never executed
unconditional 83 never executed
call   84 never executed
call   85 never executed
unconditional 86 never executed
call   87 never executed
unconditional 88 never executed
call   89 never executed
call   90 never executed
call   91 never executed
branch 92 never executed
branch 93 never executed
call   94 never executed
call   95 never executed
call   96 never executed
branch 97 never executed
branch 98 never executed
call   99 never executed
unconditional 100 never executed
unconditional 101 never executed
call   102 never executed
call   103 never executed
unconditional 104 never executed
call   105 never executed
unconditional 106 never executed
call   107 never executed
        -:   39:/*EOF*/
        -:   40:/*EOF*/
        -:   41:/*EOF*/
        -:   42:/*EOF*/
        -:   43:/*EOF*/
        -:   44:/*EOF*/
        -:   45:/*EOF*/
        -:   46:/*EOF*/
```

screen shot 2015-11-08 at 12 06 52 pm

**Comment by DarthGandalf** [comment]
In case of `if (sName.empty() || sValue.empty())` my wild guess is that it's because `||` causes right operand to not be calculated if the left operand is true.
For the rest... no idea

**Comment by stevepeak** [comment]
I read the man on gcov and read a number of articles related to gcov reports. I'm not sure getting accurate branches will happen at this time. The results above are the best I can come up with. The coverage became 18% due to the large number of partially covered lines.

I cannot make out what Codecov should report for methods of the following:

``` c
if (sName.empty() || sValue.empty()) {
```

```
call    0 never executed
branch  1 never executed
branch  2 never executed
call    3 never executed
branch  4 never executed
branch  5 never executed
unconditional  6 never executed
unconditional  7 never executed
branch  8 never executed
branch  9 never executed
call   10 returned 621
branch 11 taken 621 (fallthrough)
branch 12 taken 0
call   13 returned 621
branch 14 taken 81 (fallthrough)
branch 15 taken 540
unconditional 16 taken 81
unconditional 17 taken 540
branch 18 taken 81 (fallthrough)
branch 19 taken 540
call   20 never executed
branch 21 never executed
branch 22 never executed
call   23 never executed
branch 24 never executed
branch 25 never executed
unconditional 26 never executed
unconditional 27 never executed
branch 28 never executed
branch 29 never executed
call   30 never executed
branch 31 never executed
branch 32 never executed
call   33 never executed
branch 34 never executed
branch 35 never executed
unconditional 36 never executed
unconditional 37 never executed
branch 38 never executed
branch 39 never executed
```

My result was `5/24` which is more confusing then its worth.

Thoughts?

**Comment by DarthGandalf** [comment]
> unconditional  6 never executed

Are you counting unconditional branches too?

**Comment by stevepeak** [comment]
I was not. I just counted branches (not calls or unconditional).
Adding unconditional would make this `+2/+8  7/32`

Is this accurate?

**Comment by DarthGandalf** [comment]
Looks like clang produces more sane results than gcc:

``` c++
if (sName.empty() || sValue.empty()) {
```

```
branch  0 taken 621
branch  1 taken 0
branch  2 taken 81
branch  3 taken 540
```

Which is just `3/4`.

Need to run it on osx though: https://llvm.org/bugs/show_bug.cgi?id=20530
Just change `os: linux` to `os: osx` in the matrix.

**Comment by DarthGandalf** [comment]
> Just change os: linux to os: osx in the matrix.

Probably this won't work though on this repo...

**Comment by DarthGandalf** [comment]
This works: https://github.com/DarthGandalf/znc/compare/7229032ea01881aad3ef1f617808eb8e5bf79a2f...332b6f5b3d76d19c2e5126df326f1e9bc53e60ab

**Comment by stevepeak** [comment]
@DarthGandalf checking in to see if there were any items to help out with here.

Thanks!

**Comment by DarthGandalf** [comment]
@stevepeak what do you mean?
I've left a comment about clang above, are you referring to it?

**Pull request closed without merging**
